In [8]:
import numpy as np
from numpy import pi
from numpy import poly1d
print(np.__version__)

1.21.6


In [64]:
# arange
array = np.arange(16)
print(array)
array = np.arange(5, dtype='complex')
print(array)
array = np.arange(5, 16)
print(array)
array = np.arange(10, 0, -4)
print(array)
array = np.arange(5, 16, 3)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[ 5  6  7  8  9 10 11 12 13 14 15]
[10  6  2]
[ 5  8 11 14]


In [83]:
# linspace
array = np.linspace(5, 7, 10)  # here 10 to 20 data has broken in 50 points
print("Array : ", array)

Array :  [5.         5.22222222 5.44444444 5.66666667 5.88888889 6.11111111
 6.33333333 6.55555556 6.77777778 7.        ]


In [23]:
# zeros
array = np.zeros(10)
print(array)
array = np.zeros((2, 4), dtype='complex')
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [24]:
# ones
array = np.ones(10)
print(array)
array = np.ones((2, 4), dtype='complex')
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


In [29]:
# empty
array = np.empty(10)
print(array)
array = np.empty((3,3), dtype='int')
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[94058188861744              0              0]
 [             0              0              0]
 [             0              0              0]]


In [40]:
# eye
array = np.eye(4, dtype='float')    # default N=M=4
print(array)
array = np.eye(N=3, M=3, k=0, dtype='float')  # k=0 is default
print(array)
array = np.eye(N=3, M=3, k=2, dtype='float')  # skip 2 col
print(array)
array = np.eye(N=3, M=3, k=-1, dtype='float') # except 1st row
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [50]:
# diag
array = np.diag((-1, -2, -3))
print(array)
array = np.diag((-1, -2, -3), k=2)  # skip 2 col
print(array)
array = np.diag((-1, -2, -3), k=-2) # skip 2 row
print(array)

[[ 0  0 -1  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -3]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [-1  0  0  0  0]
 [ 0 -2  0  0  0]
 [ 0  0 -3  0  0]]


In [62]:
# vstack and hstack
x = [0, 2, 4, 6, 8]
y = [0, 1, 2, 3, 4]

vstack_array = np.vstack([x,y])
print(vstack_array)

hstack_array = np.hstack([x,y])
print(hstack_array)

dstack_array = np.dstack((arr1, arr2))  # for this len(x) should be same as len(y)
print(dstack_array)

[[0 2 4 6 8]
 [0 1 2 3 4]]
[0 2 4 6 8 0 1 2 3 4]


In [66]:
# concatenate
x = [0, 2, 4, 6, 8]
y = [0, 1, 2, 3, 4]
array = np.concatenate((x, y))
print("array : ", array)

array :  [0 2 4 6 8 0 1 2 3 4]


In [74]:
# array split
l = [1, 2, 3, 4, 5, 6]
array = np.array(l)
newarr = np.array_split(array, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [69]:
# unique
l = [10, 20, 10, 30, 20, 30, 40, 50, 40, 50]
array = np.unique(l)
print("Array : ", array)

unique_values, indices_list = np.unique(l, return_index=True)
print("unique_values = ", unique_values)
print("indices_list = ", indices_list)

Array :  [10 20 30 40 50]
unique_values =  [10 20 30 40 50]
indices_list =  [0 1 3 6 7]


In [77]:
# Random
x = np.random.randint(100)
print(x)
x = np.random.rand(5)
print(x)
x = np.random.rand(3, 5)
print(x)
x = np.random.randn(3)
print(x)

[0.38807038 0.97646385 0.87385096 0.18050781 0.5467251 ]
[[0.50107741 0.31488357 0.84938217 0.9067569  0.26688516]
 [0.82673757 0.44411163 0.65487152 0.3705027  0.31250782]
 [0.44192459 0.58127729 0.84262197 0.79083367 0.07460805]]
[-0.87909107 -0.22820506  0.13264408]


In [ ]:
# seed
np.random.seed(5555)

In [78]:
# Normal (Gaussian) Distribution
"""
loc - (Mean) where the peak of the bell exists.
scale - (Standard Deviation) how flat the graph distribution should be.
size - The shape of the returned array.
"""
Gaussian = np.random.normal(size=(2, 3))
print(x)


# Binomial Distribution
"""
lam - rate or known number of occurences e.g. 2 for above problem.
size - The shape of the returned array.
"""
x = np.random.poisson(lam=2, size=10)
print(x)


# Logistic Distribution
"""
loc - mean, where the peak is. Default 0.
scale - standard deviation, the flatness of distribution. Default 1.
size - The shape of the returned array.
"""
x = np.random.logistic(loc=1, scale=2, size=(2, 3))
print(x)


# Exponential Distribution
"""
scale - inverse of rate ( see lam in poisson distribution ) defaults to 1.0.
size - The shape of the returned array.
"""
x = np.random.exponential(scale=2, size=(2, 3))
print(x)

[[-0.16661592  2.25034356  0.42932608]
 [-0.21427361  1.02221854 -0.35430682]]


In [32]:
# poly1d
p = poly1d([3,4,5])
print(p)
print(p*p)

   2
3 x + 4 x + 5
   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [ ]:
# Basic Of Numpy
print("array.max() : ", array.max())
print("array.mean() : ", array.mean())
print("array.sum() : ", array.sum())
print("np.exp : ", np.exp(array))
print("np.sqrt : ", np.sqrt(array))
print("np.add(x,y) : ", np.add(array, array))
print("np.subtract : ", np.subtract(array, array))
print("np.power : ", np.power(array, array))
print("array.copy() : ", array.copy())
print("sorted : ", np.sort(array))
print("flatten[ravel] : ", array.ravel())
print("log(e) : ", np.log(array))
print("log2 : ", np.log2(array))
print("log10 : ", np.log10(array))
print("Lenght : ", len(array))
print("Dtype : ", array.dtype)
print("array.size : ", array.size)
array = array.reshape(2, 2)
print("array.shape : ", array.shape)
print("array.ndim : ", array.ndim)

In [56]:
# convert into numpy
l = [[5,2],[1,3],[4,6]]
array = np.array(l, dtype='complex')
print(array)

array = np.array([1,2,3,4], ndmin=2)
print("Array : ", array)

[[5.+0.j 2.+0.j]
 [1.+0.j 3.+0.j]
 [4.+0.j 6.+0.j]]
Array :  [[1 2 3 4]]


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# nditer
for x in np.nditer(arr):
  print(x)

# ndenumerate
for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [70]:
# create/read csv, xlsx with numpy
l = [i for i in range(10,50,2)]
csv_arr = np.array(l)
print(csv_arr)

# save csv
np.savetxt('new_file.csv', csv_arr)

# load csv
np.loadtxt('new_file.csv')

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48.])