In [1]:
import numpy as np

In [2]:
list_1D = [10, 20, 30, 40, 50, 60, 70, 80, 90]
list_2D = [
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80],
    [90, 100]
]
list_3D = [
    [
        [10, 20],
        [30, 40]
    ],
    [
        [50, 60],
        [70, 80]
    ]
]

In [3]:
# np array creation
array_1D = np.array(list_1D, dtype='float')
print("1D array::\n", array_1D, "shape=", array_1D.shape, "ndim=", array_1D.ndim, "size=", array_1D.size, "dtype=", array_1D.dtype, "itemsize=", array_1D.itemsize)
array_2D= np.array(list_2D, dtype='complex')
print("2D array::\n", array_2D, "shape=", array_2D.shape, "ndim=", array_2D.ndim, "size=", array_2D.size, "dtype=", array_2D.dtype, "itemsize=", array_2D.itemsize)
array_3D= np.array(list_3D, dtype='int')
print("3D array::\n", array_3D, "shape=", array_3D.shape, "ndim=", array_3D.ndim, "size=", array_3D.size, "dtype=", array_3D.dtype, "itemsize=", array_3D.itemsize)

1D array::
 [10. 20. 30. 40. 50. 60. 70. 80. 90.] shape= (9,) ndim= 1 size= 9 dtype= float64 itemsize= 8
2D array::
 [[ 10.+0.j  20.+0.j]
 [ 30.+0.j  40.+0.j]
 [ 50.+0.j  60.+0.j]
 [ 70.+0.j  80.+0.j]
 [ 90.+0.j 100.+0.j]] shape= (5, 2) ndim= 2 size= 10 dtype= complex128 itemsize= 16
3D array::
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] shape= (2, 2, 2) ndim= 3 size= 8 dtype= int64 itemsize= 8


In [4]:
list1 = [1,2,3,4,5]
list2 = [[1, 2, 3], [4, 5, 6]]

In [5]:
list3 = np.array([2, 3, 4], dtype='float')
list3 = np.array([2, 3, 4], dtype=np.float64)
print(list3)

[2. 3. 4.]


In [6]:
list4 = np.array([[1, 2], [3, 4]], dtype=complex)
print(list4)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [7]:
np_array1 = np.array(list1)
print(np_array1)

[1 2 3 4 5]


In [8]:
np_array2 = np.array(list2)
print(np_array2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(np_array1.shape)

(5,)


In [10]:
print(np_array1.ndim)

1


In [11]:
print(np_array1.dtype)

int64


In [12]:
print(np_array1.dtype.name)

int64


In [13]:
print(np_array1.max())

5


In [14]:
print(np_array1.min())

1


In [15]:
print(np_array1.sum())

15


In [16]:
print(np_array2)

[[1 2 3]
 [4 5 6]]


In [17]:
print(np_array2.sum())

21


In [18]:
max_col = np_array2.sum(axis=0) #col
print(max_col)

[5 7 9]


In [19]:
max_col = np_array2.sum(axis=1) #row
print(max_col)

[ 6 15]


In [20]:
# sort & filtering
array_700 = np.array([[1,4],[3,1]])

sorted_array = np.sort(array_700)
print("sorted_array::", sorted_array)

sorted_array = np.sort(array_700, axis=None)
print("sorted_array::", sorted_array)

sorted_array = np.sort(array_700, axis=0)
print("sorted_array::", sorted_array)

sorted_array = np.argsort(array_700, axis=None)
print("argsort_array::", sorted_array)

sorted_array = np.argmax(array_700, axis=None)
print("argmax_array::", sorted_array)

sort = np.sort(np_array1)
print(sort)

sorted_array:: [[1 4]
 [1 3]]
sorted_array:: [1 1 3 4]
sorted_array:: [[1 1]
 [3 4]]
argsort_array:: [0 3 2 1]
argmax_array:: 1
[1 2 3 4 5]


In [21]:
print(np_array1.size)

5


In [22]:
print(np_array1.data)

In [23]:
sqrt = np.sqrt(np_array1)
print(sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [24]:
exp = np.exp(np_array1)
print(exp)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [25]:
copy_np_array1 = np_array1.copy()
print(copy_np_array1)

[1 2 3 4 5]


In [26]:
# zeros & zeros_like
array_100 = np.zeros(shape=(2, 4), dtype='int')
print("zeros::\n", array_100)

array_200 = np.zeros_like(array_100)
print("zeros_like::\n", array_200)

array_200 = np.zeros_like(array_100, shape=(4, 2), dtype='complex')
print("zeros_like::\n", array_200)

zeros::
 [[0 0 0 0]
 [0 0 0 0]]
zeros_like::
 [[0 0 0 0]
 [0 0 0 0]]
zeros_like::
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [27]:
np_array = np.zeros(4)
print(np_array)

np_array = np.zeros((2,2))
print(np_array)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [28]:
# ones & ones_like
array_100 = np.ones(shape=(2, 4), dtype='int')
print("ones::\n", array_100)

array_200 = np.ones_like(array_100)
print("ones_like::\n", array_200)

ones::
 [[1 1 1 1]
 [1 1 1 1]]
ones_like::
 [[1 1 1 1]
 [1 1 1 1]]


In [29]:
np_array = np.ones(4)
print(np_array)

np_array = np.ones((2,2))
print(np_array)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [30]:
np_array = np.eye(4)
print(np_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
# empty & empty_like
array_100 = np.empty(shape=(2, 2), dtype='int')
print("empty::\n", array_100)

array_200 = np.empty_like(array_100)
print("empty_like::\n", array_200)

empty::
 [[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]
empty_like::
 [[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]


In [32]:
np_array = np.empty((4,2))
print(np_array)

[[5.e-324 5.e-324]
 [5.e-324 5.e-324]
 [5.e-324 5.e-324]
 [5.e-324 5.e-324]]


In [33]:
# identity
array_100 = np.identity(2, dtype='complex')
print("identity::\n", array_100)

identity::
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [34]:
# linspace
array_100 = np.linspace(10, 20, 2)
print("linspace::\n", array_100)

array_100 = np.linspace(10, 20, 5)
print("linspace::\n", array_100)

array_100 = np.linspace(10, 20, 10, dtype='int')
print("linspace::\n", array_100)

array_100 = np.linspace(10, 20, 20, dtype='float')
print("linspace::\n", array_100)

linspace::
 [10. 20.]
linspace::
 [10.  12.5 15.  17.5 20. ]
linspace::
 [10 11 12 13 14 15 16 17 18 20]
linspace::
 [10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


In [35]:
# logspace
array_100 = np.logspace(2.0, 3.0, num=4)
print("logspace::\n", array_100)

logspace::
 [ 100.          215.443469    464.15888336 1000.        ]


In [36]:
# arrange
''' do not touch upper limit '''
array_100 = np.arange(10)
print("arrange::\n", array_100)

array_100 = np.arange(10, 20, 2)
print("arrange[+ve]::\n", array_100)

array_100 = np.arange(20, 10, -2)
print("arrange[-ne]::\n", array_100)

arrange::
 [0 1 2 3 4 5 6 7 8 9]
arrange[+ve]::
 [10 12 14 16 18]
arrange[-ne]::
 [20 18 16 14 12]


In [37]:
np_arange = np.arange(0,10)
print(np_arange)

np_arange = np.arange(0,10, 2)
print(np_arange)

np_array = np.arange(12)
print(np_array)

new_shape = np_array.reshape((4, 3))
print(new_shape)

np_array = np.arange(24)
print(np_array)

new_shape = np_array.reshape(2, 3, 4)
print(new_shape)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [38]:
array_100 = array_1D.reshape((3, 3), order='c')
print("reshape[row major]::\n", array_100)

array_100 = array_1D.reshape((3, 3), order='f')
print("reshape[col major]::\n", array_100)

reshape[row major]::
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
reshape[col major]::
 [[10. 40. 70.]
 [20. 50. 80.]
 [30. 60. 90.]]


In [39]:
# Arithmetic Operations
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

add_ans = a+b   # np.add(a, b)
print(add_ans)

sub_ans = a-b   # np.subtract(a, b)
print(sub_ans)

sub_ans = a-b-1 # np.subtract(a, b, 1)
print(sub_ans)

mul_ans = a*b   # np.multiply(a, b)
print(mul_ans)

div_ans = a/b   # np.divide(a, b)
print(div_ans)

mod_ans = np.mod(a, b)
print(mod_ans)

rem_ans = np.remainder(a, b)
print(rem_ans)

pow_ans = np.power(a, b)
print(pow_ans)

mean_a = np.mean(a)
print(mean_a)

mean_b = np.average(b)
print(mean_b)

sum_a = np.sum(a)
print(sum_a)

[  7  77  23 130]
[ 3 67  3 70]
[ 2 66  2 69]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
[ 1  2  3 10]
[ 1  2  3 10]
[                 25          1934917632        137858491849
 1152921504606846976]
47.5
11.75
190


In [40]:
# operation
np_array0 = np_array1.copy()
print(np_array0)
np_array0 = np_array0[np_array0 >= 4]
print(np_array0)

[1 2 3 4 5]
[4 5]


In [41]:
array_where = np.arange(10, 20, 2)

array_where = np.where(array_where > 15)
print("array_where::", array_where)

array_where = np.where(array_where == 15)
print("array_where::", array_where)

array_where:: (array([3, 4]),)
array_where:: (array([], dtype=int64),)


In [42]:
# Random
my_random = np.random.rand(2)  # [+ve] [0-1]
print(my_random)
my_random = np.random.rand(2,2)
print(my_random)

my_random = np.random.randn(2)  # [-ve] [0-1]
print(my_random)
my_random = np.random.randn(2,2)
print(my_random)

num = np.random.randint(1,1000)  # [1-100]
print(num)
num = np.random.randint(0,100,4)  # 4 random numbers between 0 to 100
print(num)

[0.77015137 0.46379347]
[[0.7064548  0.60193369]
 [0.53630047 0.65224427]]
[ 1.68572701 -1.33911021]
[[ 1.38701102 -0.42004661]
 [-0.92862854  0.44648936]]
403
[62 36 37 55]


In [43]:
rg = np.random.default_rng(101)
print(rg.random((2, 2)))

[[0.94353251 0.35942103]
 [0.78480541 0.59127819]]


In [44]:
seed = np.random.seed(42)
my_random = np.random.rand(2,2)
print(my_random)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [45]:
# Reshaping and flattening multidimensional arrays
np_arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
# When you use flatten, changes to your new array won’t change the parent array.
flatten = np_arr.flatten()
print(flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [47]:
# when you use ravel, the changes you make to the new array will affect the parent array.
ravel = np_arr.ravel()
print(ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
# reshape(-1) means make any dim array to 1d
array_100 = array_2D.reshape(-1)
print("flattened array::\n", array_100)

flattened array::
 [ 10.+0.j  20.+0.j  30.+0.j  40.+0.j  50.+0.j  60.+0.j  70.+0.j  80.+0.j
  90.+0.j 100.+0.j]


In [49]:
# reverse
reversed_arr = np.flip(np_arr)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [50]:
reversed_arr_rows = np.flip(np_arr, axis=1)
print(reversed_arr_rows)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [51]:
# transpose
T = np_arr.T
print(T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# Few Useful Method
https://www.geeksforgeeks.org/python-numpy/

In [52]:
# concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

output_0 = np.concatenate((a, b), axis=0)
print("output_0::", output_0)

output_0 = np.concatenate((a, b), axis=1)
print("output_0::", output_0)

output_0 = np.concatenate((a, b), axis=None)
print("output_0::", output_0)

output_0:: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
output_0:: [[1 2 5 6]
 [3 4 7 8]]
output_0:: [1 2 3 4 5 6 7 8]


In [53]:
# asarray [help to change data type]
array_100 = np.asarray(array_1D, dtype='int').reshape((3,3), order='c')
print("asarray[order=[row major]]::\n", array_100)

array_100 = np.asarray(array_1D, dtype='int').reshape((3, 3), order='F')
print("asarray[order=[col major]::\n", array_100)

asarray[order=[row major]]::
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
asarray[order=[col major]::
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [54]:
# array_split
array_100 = np.arange(10, 20, 2)

array_100 = np.array_split(array_100, 3)
print("array_split::\n", array_100)

array_split::
 [array([10, 12]), array([14, 16]), array([18])]


In [55]:
# insert/delete
array_500 = np.arange(6).reshape((2, 3))

array_after_delete = np.delete(array_500, 5)
print("deleted_array::\n", array_after_delete)

array_after_insert = np.insert(array_500, obj=2, values=50, axis=0)
print("array_after_insert::[axis=0]\n", array_after_insert)

array_after_insert = np.insert(array_500, obj=2, values=50, axis=1)
print("array_after_insert::[axis=1]\n", array_after_insert)

deleted_array::
 [0 1 2 3 4]
array_after_insert::[axis=0]
 [[ 0  1  2]
 [ 3  4  5]
 [50 50 50]]
array_after_insert::[axis=1]
 [[ 0  1 50  2]
 [ 3  4 50  5]]


In [56]:
# Binary operations
bwt_and= np.bitwise_and(13, 17)
print("bwt_and", bwt_and)

binary_format = np.binary_repr(12)
print("binary_format", binary_format)

# left_sft = np.left_shift(5, 2)
# print("left_shift", left_shift)

bwt_and 1
binary_format 1100


In [57]:
# String operations
array_100 = np.array(["pythOn", "numPy", 55])
array_200 = np.array(["1", "2", "7"])

capitalize = np.char.capitalize(array_100)
print("capitalize:: ", capitalize)

lower = np.char.lower(array_100)
print("lower:: ", lower)

str_add = np.char.add(array_100, array_200)
print("str_add:: ", str_add)

str_multi = np.array(["a", "b", "c"])
str_multi = np.char.multiply(str_multi, 5)
print("str_multi:: ", str_multi)

str_multi = np.array(['a', 'b', 'c', 'd', 'e', 'f']).reshape((2, 3))
str_multi = np.char.multiply(str_multi, 5)
print("str_multi:: ", str_multi)

str_replace = np.array(["That is a mango", "Monkeys eat mangos"])
str_replace = np.char.replace(str_replace, 'mango', 'banana')
print("str_replace:: ", str_replace)

capitalize::  ['Python' 'Numpy' '55']
lower::  ['python' 'numpy' '55']
str_add::  ['pythOn1' 'numPy2' '557']
str_multi::  ['aaaaa' 'bbbbb' 'ccccc']
str_multi::  [['aaaaa' 'bbbbb' 'ccccc']
 ['ddddd' 'eeeee' 'fffff']]
str_replace::  ['That is a banana' 'Monkeys eat bananas']


In [58]:
# stacking
np_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

output_0 = np.vstack([np_arr, np_arr])
print("output_0::\n", output_0)

output_0 = np.hstack([np_arr, np_arr])
print("output_0::\n", output_0)

output_0::
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
output_0::
 [[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


In [59]:
# Vectorization
def add(arr1, arr2):
    print("arr1=", arr1, "arr2=", arr2)
    return (arr1 + arr2)

arr1 = np.array([1,2])
arr2 = np.array([4,5])
vectorized_add = np.vectorize(add)
result = vectorized_add(arr1, arr2)
print(result)

arr1= 1 arr2= 4
arr1= 1 arr2= 4
arr1= 2 arr2= 5
[5 7]


In [60]:
np_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np_arr)

np_arr.argmin() # return index of min value 
np_arr.argmax() # return index of max value

np.insert(np_arr, 1, 9)  # insert 9 at position 1
np.delete(np_arr, 9)     # delete 9 from array
np_arr = np.append(np_arr, np_arr)   # [......]
round_off_values = np.around(np_arr) # round value

out = np.power([1, 2, 3, 4], [0, 1, 2, 3])
out= np.equal([1., 2.], [1., 3.]) # [True, False]

a = np_arr.copy() # deep copy
b = np_arr.view() # shallow copy

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
