# Import package

In [1]:
# Data Manupulation
import numpy as np
import pandas as pd

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

# impute
from sklearn.impute import SimpleImputer, KNNImputer

# ColumnTransformer
from sklearn.compose import ColumnTransformer

# preprocessing
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder, StandardScaler, MinMaxScaler, MaxAbsScaler, PolynomialFeatures

# model_selection
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV, RepeatedKFold

# metrics
from sklearn.metrics import r2_score, mean_squared_error

# linear_model
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression, LogisticRegression, SGDRegressor

# svm
from sklearn.svm import SVR, LinearSVR

# ensemble
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, BaggingRegressor, GradientBoostingRegressor, HistGradientBoostingRegressor, StackingRegressor, VotingRegressor, ExtraTreesRegressor

# tree
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree

# cross_decomposition
from sklearn.cross_decomposition import PLSRegression

# xgboost
from xgboost import XGBRegressor, XGBRFRegressor

# lightgbm
from lightgbm import LGBMRegressor

# catboost
from catboost import CatBoostRegressor

# Read Dataset

In [2]:
df = pd.read_csv('../../test_data/iris.csv')
df.head(2)

Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width species
0           0           5.1          3.5           1.4          0.2  setosa
1           1           4.9          3.0           1.4          0.2  setosa

In [3]:
del df['Unnamed: 0']
df.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

# x, y split

In [4]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
x[0:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [6]:
y[0:2]

array(['setosa', 'setosa'], dtype=object)

# LabelEncoder

In [7]:
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
y[0:2]

array([0, 0])

# Deal with Missing Values

In [9]:
imputer = KNNImputer(n_neighbors=5, missing_values=np.nan)
x[:, :] = imputer.fit_transform(x[:, :])

In [10]:
x[0:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

# Train Test Split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Scalling

In [12]:
scaler = StandardScaler()
x_train[:, :] = scaler.fit_transform(x_train[:, :])
x_test[:, :] = scaler.fit_transform(x_test[:, :])

In [13]:
x_train[0:2]

array([[-1.01827123,  1.2864604 , -1.39338902, -1.3621769 ],
       [-0.7730102 ,  2.43545215, -1.33550342, -1.49647603]])

In [14]:
y_train[0:2]

array([0, 0])

In [15]:
x_test[0:2]

array([[ 0.25621067, -0.71903739,  0.58987181,  0.05585913],
       [-0.21299441,  1.61629772, -1.03834577, -1.06789518]])

In [16]:
y_test[0:2]

array([1, 0])

# Model Quality

In [17]:
def print_training_score(regressor=None, X_train=None, Y_train=None):
    training_score = regressor.score(X_train, Y_train)
    print("training_score = ", training_score)

    
def print_training_cross_val_score(regressor=None, X_train=None, Y_train=None, cv=5):    
    accuracies = cross_val_score(estimator=regressor, X=X_train, y=Y_train, cv=cv)
    print("Training Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Training data Standard Deviation: {:.2f} %".format(accuracies.std()*100))

    
def print_r2_score(Y_test=None, Y_pred=None):
    r_2_score = r2_score(Y_test, Y_pred)
    print("r_2_score = ", r_2_score)

    
def print_mse_and_rmse(Y_test=None, Y_pred=None):
    mse = mean_squared_error(Y_test, Y_pred, squared=False)
    print("MSE = ", mse)
    rmse = mean_squared_error(Y_test, Y_pred, squared=True)
    print("RMSE = ", rmse)

    
def print_summary(regressor=None, x_train=None, y_train=None, y_test=None, y_pred=None):
    print_training_score(regressor=regressor, X_train=x_train, Y_train=y_train)
    print_training_cross_val_score(regressor=regressor, X_train=x_train, Y_train=y_train)

    print_r2_score(Y_test=y_test, Y_pred=y_pred)
    print_mse_and_rmse(Y_test=y_test, Y_pred=y_pred)

    np.set_printoptions(precision=2)
    print("Compare with Predict and actual\n", np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), 1)[0:10])

# LinearRegression

In [18]:
params = {
    'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': 'deprecated', 'positive': False
}
regressor = LinearRegression()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9225512936540917
Training Accuracy: 91.13 %
Training data Standard Deviation: 2.13 %
r_2_score =  0.9301678301266041
MSE =  0.22177094563474958
RMSE =  0.049182352327731056
Compare with Predict and actual
 [[1.   1.31]
 [0.   0.11]
 [2.   2.23]
 [1.   1.41]
 [1.   1.36]
 [0.   0.17]
 [1.   1.14]
 [2.   1.85]
 [1.   1.43]
 [1.   1.15]]


# Lasso

In [19]:
params = {
    'alpha': 0.3, 'copy_X': True, 'fit_intercept': True, 'max_iter': 1000, 'normalize': 'deprecated',
    'positive': False, 'precompute': False, 'random_state': None, 'selection': 'cyclic', 'tol': 0.0001,
    'warm_start': False
}
regressor = Lasso(alpha=0.3)
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.7755632913093676
Training Accuracy: 75.51 %
Training data Standard Deviation: 1.73 %
r_2_score =  0.7630458465204102
MSE =  0.4085159735132433
RMSE =  0.1668853006154729
Compare with Predict and actual
 [[1.   1.17]
 [0.   0.53]
 [2.   1.78]
 [1.   1.24]
 [1.   1.24]
 [0.   0.54]
 [1.   1.07]
 [2.   1.57]
 [1.   1.24]
 [1.   1.07]]


# Ridge

In [20]:
params = {
    'alpha': 0.1, 'copy_X': True, 'fit_intercept': True, 'max_iter': None, 'normalize': 'deprecated', 
    'positive': False, 'random_state': None, 'solver': 'auto', 'tol': 0.001
}
regressor = Ridge(alpha=0.01)
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9225483224765989
Training Accuracy: 91.15 %
Training data Standard Deviation: 2.13 %
r_2_score =  0.9302304885682077
MSE =  0.2216714288908667
RMSE =  0.04913822238651857
Compare with Predict and actual
 [[1.   1.31]
 [0.   0.11]
 [2.   2.23]
 [1.   1.41]
 [1.   1.36]
 [0.   0.17]
 [1.   1.14]
 [2.   1.85]
 [1.   1.43]
 [1.   1.15]]


# ElasticNet

In [21]:
params = {
    'alpha': 0.2, 'copy_X': True, 'fit_intercept': True, 'l1_ratio': 0.5, 'max_iter': 1000, 
    'normalize': 'deprecated', 'positive': False, 'precompute': False, 'random_state': None, 
    'selection': 'cyclic', 'tol': 0.0001, 'warm_start': False
}
regressor = ElasticNet()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.8891480300369239
Training Accuracy: 88.17 %
Training data Standard Deviation: 1.46 %
r_2_score =  0.8884004119322245
MSE =  0.2803549158724134
RMSE =  0.078598878853828
Compare with Predict and actual
 [[1.   1.23]
 [0.   0.35]
 [2.   2.06]
 [1.   1.32]
 [1.   1.33]
 [0.   0.35]
 [1.   1.08]
 [2.   1.75]
 [1.   1.32]
 [1.   1.09]]


# Polynomial

In [22]:
poly_features = PolynomialFeatures(degree=2, include_bias=True)
ploy_x_train = poly_features.fit_transform(x_train)
ploy_x_test = poly_features.fit_transform(x_test)

params = {
    'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': 'deprecated', 'positive': False
}
regressor = LinearRegression()
regressor.set_params(**params)
regressor.fit(ploy_x_train, y_train)
y_pred = regressor.predict(ploy_x_test)

print_summary(regressor, ploy_x_train, y_train, y_test, y_pred)

training_score =  0.9486949445238945
Training Accuracy: 91.39 %
Training data Standard Deviation: 2.77 %
r_2_score =  0.9192429064924624
MSE =  0.238488377994569
RMSE =  0.056876706438480425
Compare with Predict and actual
 [[1.   1.34]
 [0.   0.09]
 [2.   2.74]
 [1.   1.4 ]
 [1.   1.23]
 [0.   0.1 ]
 [1.   1.01]
 [2.   1.88]
 [1.   1.54]
 [1.   1.1 ]]


# Support Vector

In [23]:
# kernel: {‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}
# gamma: {`scale`, `auto`}
# C: The strength of the regularization is inversely proportional to C
params = {
    'C': 0.4, 'cache_size': 200, 'coef0': 0.0, 'degree': 3, 'epsilon': 0.1, 'gamma': 'scale', 'kernel': 'rbf', 
    'max_iter': -1, 'shrinking': True, 'tol': 0.001, 'verbose': False
}
regressor = SVR()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9456054542155697
Training Accuracy: 92.16 %
Training data Standard Deviation: 3.22 %
r_2_score =  0.9533803905438915
MSE =  0.18120125252738942
RMSE =  0.03283389391749475
Compare with Predict and actual
 [[1.   1.23]
 [0.   0.07]
 [2.   1.78]
 [1.   1.39]
 [1.   1.36]
 [0.   0.09]
 [1.   0.96]
 [2.   1.97]
 [1.   1.32]
 [1.   1.06]]


# LinearSVR

In [24]:
# dual = False when n_samples > n_features
# C: The strength of the regularization is inversely proportional to C
params = {
    'C': 1.0, 'dual': True, 'epsilon': 0.0, 'fit_intercept': True, 'intercept_scaling': 1.0, 
    'loss': 'epsilon_insensitive', 'max_iter': 10000, 'random_state': None, 'tol': 0.0001, 'verbose': 0
}
regressor = LinearSVR()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9211384103614587
Training Accuracy: 91.07 %
Training data Standard Deviation: 2.13 %
r_2_score =  0.929745432823939
MSE =  0.222440652887066
RMSE =  0.049479844056824186
Compare with Predict and actual
 [[1.   1.27]
 [0.   0.15]
 [2.   2.22]
 [1.   1.39]
 [1.   1.36]
 [0.   0.22]
 [1.   1.13]
 [2.   1.88]
 [1.   1.44]
 [1.   1.14]]


# Random Forest

In [25]:
# criterion(The function to measure the quality of a split) : {“squared_error”, “absolute_error”, “friedman_mse”, “poisson”}
# max_depth : The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.
# min_samples_split : The minimum number of samples required to split an internal node.
# bootstrap : Whether bootstrap samples are used when building trees. If False, the whole dataset is used to build each tree.
# oob_score : Whether to use out-of-bag samples to estimate the generalization score. Only available if bootstrap=True.
# ccp_alpha : The subtree with the largest cost complexity that is smaller than ccp_alpha will be chosen. By default, no pruning is performed.
params = {
    'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 'auto', 
    'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 
    'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 
    'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False
}
regressor = RandomForestRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9884571568507408
Training Accuracy: 93.82 %
Training data Standard Deviation: 6.76 %
r_2_score =  0.9934985250737464
MSE =  0.06766791978789545
RMSE =  0.004578947368421052
Compare with Predict and actual
 [[1.   1.23]
 [0.   0.  ]
 [2.   1.97]
 [1.   1.  ]
 [1.   1.28]
 [0.   0.  ]
 [1.   1.  ]
 [2.   1.99]
 [1.   1.11]
 [1.   1.  ]]


# Decision Tree

In [26]:
# splitter : The strategy used to choose the split at each node.
params = {
    'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': None, 
    'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 
    'min_weight_fraction_leaf': 0.0, 'random_state': None, 'splitter': 'best'
}
regressor = DecisionTreeRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  1.0
Training Accuracy: 90.62 %
Training data Standard Deviation: 6.62 %
r_2_score =  1.0
MSE =  0.0
RMSE =  0.0
Compare with Predict and actual
 [[1. 1.]
 [0. 0.]
 [2. 2.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [2. 2.]
 [1. 1.]
 [1. 1.]]


# SGD

In [27]:
# penalty : {‘l2’, ‘l1’, ‘elasticnet’, None}
# alpha : The higher the value, the stronger the regularization.
# learning_rate : {constant, optimal, invscaling, adaptive}
# n_iter_no_change : Number of iterations with no improvement to wait before stopping fitting.
params = {
    'alpha': 0.0001, 'average': False, 'early_stopping': False, 'epsilon': 0.1, 'eta0': 0.01, 
    'fit_intercept': True, 'l1_ratio': 0.25, 'learning_rate': 'invscaling', 'loss': 'squared_error', 
    'max_iter': 1000, 'n_iter_no_change': 10, 'penalty': 'elasticnet', 'power_t': 0.25, 'random_state': None, 
    'shuffle': True, 'tol': 0.001, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False
}
regressor = SGDRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.91376773366571
Training Accuracy: 90.50 %
Training data Standard Deviation: 2.16 %
r_2_score =  0.923736112975819
MSE =  0.23175886118836903
RMSE =  0.0537121697393297
Compare with Predict and actual
 [[1.   1.3 ]
 [0.   0.15]
 [2.   2.35]
 [1.   1.38]
 [1.   1.47]
 [0.   0.22]
 [1.   1.1 ]
 [2.   1.88]
 [1.   1.54]
 [1.   1.16]]


# Voting

In [28]:
r1 = LinearRegression()
r2 = RandomForestRegressor(n_estimators=10, random_state=1)

estimators = [
    ('r1', r1),
    ('r2', r2)
]

regressor = VotingRegressor(estimators=estimators)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9663109650788814
Training Accuracy: 93.89 %
Training data Standard Deviation: 3.89 %
r_2_score =  0.974516797648923
MSE =  0.13396886600068922
RMSE =  0.01794765705751062
Compare with Predict and actual
 [[1.   1.26]
 [0.   0.06]
 [2.   2.07]
 [1.   1.21]
 [1.   1.28]
 [0.   0.08]
 [1.   1.07]
 [2.   1.92]
 [1.   1.22]
 [1.   1.08]]


# Bagging

In [29]:
params = {
    'base_estimator': DecisionTreeRegressor(), 'bootstrap': True, 'bootstrap_features': False, 
    'max_features': 1.0, 'max_samples': 1.0, 'n_estimators': 10, 'n_jobs': None, 'oob_score': False, 
    'random_state': None, 'verbose': 0, 'warm_start': False
}
regressor = BaggingRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9897147055222236
Training Accuracy: 92.00 %
Training data Standard Deviation: 6.78 %
r_2_score =  0.9981317600786628
MSE =  0.03627381250550058
RMSE =  0.0013157894736842105
Compare with Predict and actual
 [[1.  1.1]
 [0.  0. ]
 [2.  2. ]
 [1.  1. ]
 [1.  1. ]
 [0.  0. ]
 [1.  1. ]
 [2.  2. ]
 [1.  1. ]
 [1.  1. ]]


# Stacking

In [30]:
estimators = [
    ('r1', Ridge()),
    ('r2', LinearRegression())
]

final_estimator = RandomForestRegressor(n_estimators=10, random_state=42)

regressor = StackingRegressor(
    estimators=estimators, final_estimator=final_estimator
)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9690069793069671
Training Accuracy: 95.51 %
Training data Standard Deviation: 7.54 %
r_2_score =  0.9887905604719764
MSE =  0.08885233166386386
RMSE =  0.007894736842105263
Compare with Predict and actual
 [[1.  1. ]
 [0.  0. ]
 [2.  2. ]
 [1.  1. ]
 [1.  1. ]
 [0.  0. ]
 [1.  1. ]
 [2.  2. ]
 [1.  1.2]
 [1.  1. ]]


# Gradient Boosting

In [31]:
params = {
    'alpha': 0.9, 'ccp_alpha': 0.0, 'criterion': 'friedman_mse', 'init': None, 'learning_rate': 0.1,
    'loss': 'squared_error', 'max_depth': 3, 'max_features': None, 'max_leaf_nodes': None, 
    'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0,
    'n_estimators': 100, 'n_iter_no_change': None, 'random_state': None, 'subsample': 1.0, 'tol': 0.0001,
    'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False
}
regressor = GradientBoostingRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9992469583377009
Training Accuracy: 91.63 %
Training data Standard Deviation: 6.54 %
r_2_score =  0.9939411529848721
MSE =  0.06532386509295227
RMSE =  0.0042672073506822275
Compare with Predict and actual
 [[1.00e+00 1.10e+00]
 [0.00e+00 4.56e-04]
 [2.00e+00 1.93e+00]
 [1.00e+00 1.02e+00]
 [1.00e+00 1.01e+00]
 [0.00e+00 4.56e-04]
 [1.00e+00 1.01e+00]
 [2.00e+00 1.98e+00]
 [1.00e+00 1.36e+00]
 [1.00e+00 9.98e-01]]


# HistGradientBoosting

This estimator is much faster than GradientBoostingRegressor for big datasets (n_samples >= 10 000)

In [32]:
# loss : {‘squared_error’, ‘absolute_error’, ‘poisson’, ‘quantile’}
# max_bins : The maximum number of bins to use for non-missing values.
# validation_fraction : Proportion (or absolute size) of training data to set aside as validation data for early stopping. If None, early stopping is done on the training data.
# scoring : Scoring parameter to use for early stopping.
# interaction_cst : Specify interaction constraints, the sets of features which can interact with each other in child node splits.
# monotonic_cst : Monotonic constraint to enforce on each feature are specified using the {1, 0, -1} integer values.
params = {
    'categorical_features': None, 'early_stopping': 'auto', 'l2_regularization': 0.0, 'learning_rate': 0.1,
    'loss': 'squared_error', 'max_bins': 255, 'max_depth': None, 'max_iter': 100, 'max_leaf_nodes': 31,
    'min_samples_leaf': 20, 'monotonic_cst': None, 'n_iter_no_change': 10, 'random_state': None,
    'scoring': 'loss', 'tol': 1e-07, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False
}
regressor = HistGradientBoostingRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9711117206105693
Training Accuracy: 92.08 %
Training data Standard Deviation: 6.50 %
r_2_score =  0.9819071685213799
MSE =  0.11288341746024777
RMSE =  0.012742665937504572
Compare with Predict and actual
 [[ 1.00e+00  1.37e+00]
 [ 0.00e+00 -9.52e-04]
 [ 2.00e+00  2.07e+00]
 [ 1.00e+00  1.20e+00]
 [ 1.00e+00  1.32e+00]
 [ 0.00e+00 -1.22e-02]
 [ 1.00e+00  1.02e+00]
 [ 2.00e+00  1.95e+00]
 [ 1.00e+00  1.20e+00]
 [ 1.00e+00  1.03e+00]]


# Extra Trees

This class implements a meta estimator that fits a number of randomized decision trees (a.k.a. extra-trees) on various sub-samples of the dataset and uses averaging to improve the predictive accuracy and control over-fitting.

In [33]:
params = {
    'bootstrap': False, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 
    'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0,
    'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100,
    'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False
}
regressor = ExtraTreesRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  1.0
Training Accuracy: 93.78 %
Training data Standard Deviation: 6.19 %
r_2_score =  0.9937937069813176
MSE =  0.06611393674240665
RMSE =  0.004371052631578948
Compare with Predict and actual
 [[1.   1.21]
 [0.   0.06]
 [2.   2.  ]
 [1.   1.07]
 [1.   1.17]
 [0.   0.  ]
 [1.   0.99]
 [2.   1.97]
 [1.   1.25]
 [1.   1.  ]]


# PLS

In [34]:
params = {
    'copy': True, 'max_iter': 500, 'n_components': 2, 'scale': True, 'tol': 1e-06
}
regressor = PLSRegression()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9130707945053103
Training Accuracy: 90.26 %
Training data Standard Deviation: 2.25 %
r_2_score =  0.915940046610332
MSE =  0.24331643925208446
RMSE =  0.0592028896103133
Compare with Predict and actual
 [[1.   1.33]
 [0.   0.06]
 [2.   2.33]
 [1.   1.41]
 [1.   1.45]
 [0.   0.2 ]
 [1.   1.16]
 [2.   1.87]
 [1.   1.63]
 [1.   1.22]]


# XGBoost


XGBoost does not support categorical variables natively, so it is necessary to encode them prior to training

In [35]:
# objective : {reg:linear, binary:logistic, multi:softmax, multi:softprob, reg:squarederror}
# base_score : The initial prediction score of all instances, global bias.
# booster : {gbtree, gblinear, dart} gbtree and dart use tree based models while gblinear uses linear functions.
# colsample_bylevel/colsample_bytree/colsample_bynode: This is a family of parameters for subsampling of columns.
# gamma : Minimum loss reduction required to make a further partition on a leaf node of the tree.
# Subsample[0-1] : Subsample ratio of the training instances. Setting it to 0.5 means that XGBoost would randomly sample half of the training data prior to growing trees. and this will prevent overfitting. Subsampling will occur once in every boosting iteration.
# reg_alpha : L1 regularization.
# reg_lambda : L2 regularization.
# scale_pos_weight : Control the balance of positive and negative weights, useful for unbalanced classes.
# n_estimators : Number of gradient boosted trees.
# num_parallel_tree : Used for boosting random forest.
# validate_parameters : Give warnings for unknown parameter.
# predictor : [cpu_predictor, gpu_predictor]  Force XGBoost to use specific predictor.
params = {
    'objective': 'reg:squarederror', 'base_score': None, 'booster': None, 'colsample_bylevel': None,
    'colsample_bynode': None, 'colsample_bytree': None, 'enable_categorical': False, 'gamma': None, 
    'gpu_id': None, 'importance_type': None, 'interaction_constraints': None, 'learning_rate': None,
    'max_delta_step': None, 'max_depth': None, 'min_child_weight': None, 'missing': np.nan,
    'monotone_constraints': None, 'n_estimators': 100, 'n_jobs': None, 'num_parallel_tree': None,
    'predictor': None, 'random_state': None, 'reg_alpha': None, 'reg_lambda': None, 'scale_pos_weight': None,
    'subsample': None, 'tree_method': 'auto', 'validate_parameters': None, 'verbosity': None
}
regressor = XGBRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9999967006210447
Training Accuracy: 90.08 %
Training data Standard Deviation: 8.39 %
r_2_score =  0.9918723975765179
MSE =  0.07565856596810405
RMSE =  0.005724218604349952
Compare with Predict and actual
 [[1.00e+00 1.19e+00]
 [0.00e+00 6.71e-05]
 [2.00e+00 1.95e+00]
 [1.00e+00 1.14e+00]
 [1.00e+00 9.02e-01]
 [0.00e+00 6.71e-05]
 [1.00e+00 1.00e+00]
 [2.00e+00 2.01e+00]
 [1.00e+00 1.28e+00]
 [1.00e+00 1.00e+00]]


# AdaBoost

In [36]:
# loss : {‘linear’, ‘square’, ‘exponential’}
# learning_rate (0.0, inf): Weight applied to each regressor at each boosting iteration. A higher learning rate increases the contribution of each regressor.
params = {
    'base_estimator': DecisionTreeRegressor(max_depth=3), 
    'learning_rate': 1.0, 'loss': 'linear', 'n_estimators': 50, 'random_state': None
}
regressor = AdaBoostRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9705630482977163
Training Accuracy: 91.27 %
Training data Standard Deviation: 7.17 %
r_2_score =  0.9995029555409282
MSE =  0.018710030618869257
RMSE =  0.00035006524575902505
Compare with Predict and actual
 [[1.   1.03]
 [0.   0.  ]
 [2.   2.  ]
 [1.   1.03]
 [1.   1.03]
 [0.   0.  ]
 [1.   1.  ]
 [2.   2.  ]
 [1.   1.09]
 [1.   1.  ]]


# Light GBM

- Light GBM grows tree vertically while other algorithm grows trees horizontally meaning that Light GBM grows tree leaf-wise while other algorithm grows level-wise.
- it is not advisable to use LGBM on small datasets.
- LGBM also supports GPU learning and thus data scientists are widely using LGBM for data science application development

In [37]:
# boosting_type : gbdt’, traditional Gradient Boosting Decision Tree. ‘dart’, Dropouts meet Multiple Additive Regression Trees. ‘rf’, Random Forest.
# subsample_for_bin : Number of samples for constructing bins.
# min_split_gain : Minimum loss reduction required to make a further partition on a leaf node of the tree.
params = {
    'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 
    'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 
    'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'num_leaves': 31, 'objective': None, 
    'random_state': None, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'silent': 'warn', 'subsample': 1.0,
    'subsample_for_bin': 200000, 'subsample_freq': 0
}
regressor = LGBMRegressor()
regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

training_score =  0.9669729374919923
Training Accuracy: 90.82 %
Training data Standard Deviation: 7.64 %
r_2_score =  0.96998083862817
MSE =  0.1454039342533932
RMSE =  0.021142304096365094
Compare with Predict and actual
 [[1.   1.4 ]
 [0.   0.09]
 [2.   2.08]
 [1.   1.22]
 [1.   1.31]
 [0.   0.21]
 [1.   1.1 ]
 [2.   1.97]
 [1.   1.2 ]
 [1.   1.04]]


# Cat Boost

In [38]:
params = {
    'nan_mode': 'Min', 'eval_metric': 'RMSE', 'iterations': 1000, 'sampling_frequency': 'PerTree',
    'leaf_estimation_method': 'Newton', 'grow_policy': 'SymmetricTree', 'penalties_coefficient': 1,
    'boosting_type': 'Plain', 'model_shrink_mode': 'Constant', 'feature_border_type': 'GreedyLogSum', 
    'bayesian_matrix_reg': 0.10000000149011612, 'eval_fraction': 0, 'force_unit_auto_pair_weights': False,
    'l2_leaf_reg': 3, 'random_strength': 1, 'rsm': 1, 'boost_from_average': True, 'model_size_reg': 0.5,
    'pool_metainfo_options': {'tags': {}}, 'subsample': 0.800000011920929, 'use_best_model': False,
    'random_seed': 0, 'depth': 6, 'posterior_sampling': False, 'border_count': 254, 'classes_count': 0,
    'auto_class_weights': 'None', 'sparse_features_conflict_fraction': 0, 
    'leaf_estimation_backtracking': 'AnyImprovement', 'best_model_min_trees': 1, 'model_shrink_rate': 0,
    'min_data_in_leaf': 1, 'loss_function': 'RMSE', 'learning_rate': 0.028970999643206596,
    'score_function': 'Cosine', 'task_type': 'CPU', 'leaf_estimation_iterations': 1, 'bootstrap_type': 'MVS',
    'max_leaves': 64
}
regressor = CatBoostRegressor()
# regressor.set_params(**params)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)

print_summary(regressor, x_train, y_train, y_test, y_pred)

Learning rate set to 0.028971
0:	learn: 0.7885316	total: 48.5ms	remaining: 48.5s
1:	learn: 0.7722834	total: 49.7ms	remaining: 24.8s
2:	learn: 0.7546522	total: 50.6ms	remaining: 16.8s
3:	learn: 0.7381380	total: 51.4ms	remaining: 12.8s
4:	learn: 0.7216270	total: 51.8ms	remaining: 10.3s
5:	learn: 0.7072162	total: 52.1ms	remaining: 8.63s
6:	learn: 0.6930156	total: 52.4ms	remaining: 7.43s
7:	learn: 0.6785189	total: 52.7ms	remaining: 6.53s
8:	learn: 0.6647331	total: 53ms	remaining: 5.83s
9:	learn: 0.6495870	total: 53.3ms	remaining: 5.27s
10:	learn: 0.6385574	total: 53.6ms	remaining: 4.82s
11:	learn: 0.6255637	total: 53.9ms	remaining: 4.43s
12:	learn: 0.6116135	total: 54.1ms	remaining: 4.11s
13:	learn: 0.5986482	total: 54.4ms	remaining: 3.83s
14:	learn: 0.5867086	total: 54.7ms	remaining: 3.59s
15:	learn: 0.5749941	total: 54.9ms	remaining: 3.38s
16:	learn: 0.5631658	total: 55.2ms	remaining: 3.19s
17:	learn: 0.5518121	total: 55.4ms	remaining: 3.02s
18:	learn: 0.5403781	total: 55.6ms	remaining: 

177:	learn: 0.1155393	total: 95.5ms	remaining: 441ms
178:	learn: 0.1151179	total: 96.3ms	remaining: 442ms
179:	learn: 0.1142257	total: 97.5ms	remaining: 444ms
180:	learn: 0.1132415	total: 98ms	remaining: 444ms
181:	learn: 0.1130474	total: 100ms	remaining: 450ms
182:	learn: 0.1124171	total: 102ms	remaining: 457ms
183:	learn: 0.1116551	total: 103ms	remaining: 457ms
184:	learn: 0.1108817	total: 103ms	remaining: 456ms
185:	learn: 0.1106652	total: 104ms	remaining: 455ms
186:	learn: 0.1100334	total: 109ms	remaining: 473ms
187:	learn: 0.1098450	total: 109ms	remaining: 471ms
188:	learn: 0.1096515	total: 109ms	remaining: 469ms
189:	learn: 0.1091438	total: 110ms	remaining: 467ms
190:	learn: 0.1087499	total: 110ms	remaining: 465ms
191:	learn: 0.1081337	total: 110ms	remaining: 463ms
192:	learn: 0.1077144	total: 110ms	remaining: 461ms
193:	learn: 0.1071417	total: 111ms	remaining: 459ms
194:	learn: 0.1065282	total: 111ms	remaining: 458ms
195:	learn: 0.1058698	total: 111ms	remaining: 456ms
196:	learn

388:	learn: 0.0525015	total: 170ms	remaining: 267ms
389:	learn: 0.0521451	total: 171ms	remaining: 267ms
390:	learn: 0.0519349	total: 171ms	remaining: 266ms
391:	learn: 0.0517663	total: 171ms	remaining: 266ms
392:	learn: 0.0514722	total: 172ms	remaining: 265ms
393:	learn: 0.0513353	total: 172ms	remaining: 264ms
394:	learn: 0.0513094	total: 172ms	remaining: 264ms
395:	learn: 0.0510799	total: 173ms	remaining: 263ms
396:	learn: 0.0509259	total: 173ms	remaining: 263ms
397:	learn: 0.0508635	total: 173ms	remaining: 262ms
398:	learn: 0.0507293	total: 173ms	remaining: 261ms
399:	learn: 0.0505056	total: 173ms	remaining: 260ms
400:	learn: 0.0501855	total: 174ms	remaining: 259ms
401:	learn: 0.0501632	total: 174ms	remaining: 259ms
402:	learn: 0.0501361	total: 174ms	remaining: 258ms
403:	learn: 0.0499158	total: 174ms	remaining: 257ms
404:	learn: 0.0498923	total: 174ms	remaining: 256ms
405:	learn: 0.0497179	total: 175ms	remaining: 255ms
406:	learn: 0.0495125	total: 175ms	remaining: 255ms
407:	learn: 

723:	learn: 0.0217782	total: 255ms	remaining: 97.1ms
724:	learn: 0.0217005	total: 255ms	remaining: 96.7ms
725:	learn: 0.0216392	total: 255ms	remaining: 96.3ms
726:	learn: 0.0215704	total: 255ms	remaining: 95.9ms
727:	learn: 0.0214827	total: 256ms	remaining: 95.6ms
728:	learn: 0.0214154	total: 256ms	remaining: 95.2ms
729:	learn: 0.0214088	total: 257ms	remaining: 95ms
730:	learn: 0.0213883	total: 257ms	remaining: 94.7ms
731:	learn: 0.0213620	total: 257ms	remaining: 94.3ms
732:	learn: 0.0213034	total: 258ms	remaining: 93.9ms
733:	learn: 0.0212779	total: 258ms	remaining: 93.5ms
734:	learn: 0.0212020	total: 258ms	remaining: 93.1ms
735:	learn: 0.0211438	total: 259ms	remaining: 92.8ms
736:	learn: 0.0210989	total: 259ms	remaining: 92.4ms
737:	learn: 0.0210736	total: 259ms	remaining: 92ms
738:	learn: 0.0210140	total: 260ms	remaining: 91.7ms
739:	learn: 0.0209717	total: 260ms	remaining: 91.3ms
740:	learn: 0.0209133	total: 260ms	remaining: 90.9ms
741:	learn: 0.0208721	total: 260ms	remaining: 90.5

964:	learn: 0.0135722	total: 334ms	remaining: 12.1ms
965:	learn: 0.0135685	total: 335ms	remaining: 11.8ms
966:	learn: 0.0135469	total: 335ms	remaining: 11.4ms
967:	learn: 0.0135231	total: 335ms	remaining: 11.1ms
968:	learn: 0.0134873	total: 335ms	remaining: 10.7ms
969:	learn: 0.0134465	total: 336ms	remaining: 10.4ms
970:	learn: 0.0134399	total: 336ms	remaining: 10ms
971:	learn: 0.0134367	total: 336ms	remaining: 9.68ms
972:	learn: 0.0134097	total: 336ms	remaining: 9.33ms
973:	learn: 0.0133595	total: 337ms	remaining: 8.98ms
974:	learn: 0.0133561	total: 337ms	remaining: 8.64ms
975:	learn: 0.0133312	total: 337ms	remaining: 8.29ms
976:	learn: 0.0132932	total: 338ms	remaining: 7.95ms
977:	learn: 0.0132897	total: 338ms	remaining: 7.6ms
978:	learn: 0.0132594	total: 338ms	remaining: 7.25ms
979:	learn: 0.0132558	total: 338ms	remaining: 6.9ms
980:	learn: 0.0132132	total: 339ms	remaining: 6.56ms
981:	learn: 0.0131822	total: 339ms	remaining: 6.21ms
982:	learn: 0.0131451	total: 339ms	remaining: 5.87

242:	learn: 0.0853558	total: 54.7ms	remaining: 170ms
243:	learn: 0.0850287	total: 55ms	remaining: 171ms
244:	learn: 0.0846215	total: 55.3ms	remaining: 170ms
245:	learn: 0.0841206	total: 55.5ms	remaining: 170ms
246:	learn: 0.0836983	total: 55.8ms	remaining: 170ms
247:	learn: 0.0831433	total: 56.2ms	remaining: 170ms
248:	learn: 0.0829700	total: 56.5ms	remaining: 170ms
249:	learn: 0.0824125	total: 56.7ms	remaining: 170ms
250:	learn: 0.0821279	total: 56.9ms	remaining: 170ms
251:	learn: 0.0816474	total: 57.2ms	remaining: 170ms
252:	learn: 0.0812618	total: 57.5ms	remaining: 170ms
253:	learn: 0.0809924	total: 57.7ms	remaining: 170ms
254:	learn: 0.0805916	total: 58ms	remaining: 169ms
255:	learn: 0.0802033	total: 58.2ms	remaining: 169ms
256:	learn: 0.0796655	total: 58.5ms	remaining: 169ms
257:	learn: 0.0794630	total: 58.7ms	remaining: 169ms
258:	learn: 0.0789592	total: 59ms	remaining: 169ms
259:	learn: 0.0786681	total: 59.2ms	remaining: 169ms
260:	learn: 0.0782677	total: 59.5ms	remaining: 168ms

546:	learn: 0.0313687	total: 130ms	remaining: 108ms
547:	learn: 0.0313481	total: 130ms	remaining: 107ms
548:	learn: 0.0312472	total: 130ms	remaining: 107ms
549:	learn: 0.0311752	total: 131ms	remaining: 107ms
550:	learn: 0.0311445	total: 131ms	remaining: 107ms
551:	learn: 0.0310503	total: 131ms	remaining: 107ms
552:	learn: 0.0309578	total: 131ms	remaining: 106ms
553:	learn: 0.0308339	total: 132ms	remaining: 106ms
554:	learn: 0.0308141	total: 132ms	remaining: 106ms
555:	learn: 0.0307947	total: 132ms	remaining: 106ms
556:	learn: 0.0307755	total: 132ms	remaining: 105ms
557:	learn: 0.0307179	total: 133ms	remaining: 105ms
558:	learn: 0.0306275	total: 133ms	remaining: 105ms
559:	learn: 0.0305386	total: 133ms	remaining: 105ms
560:	learn: 0.0305199	total: 133ms	remaining: 104ms
561:	learn: 0.0304188	total: 134ms	remaining: 104ms
562:	learn: 0.0304002	total: 134ms	remaining: 104ms
563:	learn: 0.0303008	total: 134ms	remaining: 104ms
564:	learn: 0.0302824	total: 135ms	remaining: 104ms
565:	learn: 

876:	learn: 0.0134871	total: 212ms	remaining: 29.8ms
877:	learn: 0.0134773	total: 213ms	remaining: 29.5ms
878:	learn: 0.0134299	total: 213ms	remaining: 29.3ms
879:	learn: 0.0134133	total: 213ms	remaining: 29.1ms
880:	learn: 0.0133901	total: 213ms	remaining: 28.8ms
881:	learn: 0.0133440	total: 214ms	remaining: 28.6ms
882:	learn: 0.0133356	total: 214ms	remaining: 28.3ms
883:	learn: 0.0132987	total: 214ms	remaining: 28.1ms
884:	learn: 0.0132539	total: 214ms	remaining: 27.8ms
885:	learn: 0.0132381	total: 215ms	remaining: 27.6ms
886:	learn: 0.0132025	total: 215ms	remaining: 27.4ms
887:	learn: 0.0131929	total: 215ms	remaining: 27.1ms
888:	learn: 0.0131474	total: 215ms	remaining: 26.9ms
889:	learn: 0.0131290	total: 216ms	remaining: 26.7ms
890:	learn: 0.0131210	total: 216ms	remaining: 26.4ms
891:	learn: 0.0131065	total: 216ms	remaining: 26.2ms
892:	learn: 0.0130634	total: 217ms	remaining: 25.9ms
893:	learn: 0.0130293	total: 217ms	remaining: 25.7ms
894:	learn: 0.0130151	total: 217ms	remaining: 

89:	learn: 0.2082136	total: 21ms	remaining: 213ms
90:	learn: 0.2063739	total: 21.5ms	remaining: 215ms
91:	learn: 0.2047304	total: 21.8ms	remaining: 215ms
92:	learn: 0.2027985	total: 22.1ms	remaining: 215ms
93:	learn: 0.2010961	total: 22.4ms	remaining: 216ms
94:	learn: 0.1999068	total: 22.6ms	remaining: 216ms
95:	learn: 0.1984660	total: 22.9ms	remaining: 215ms
96:	learn: 0.1969707	total: 23.1ms	remaining: 215ms
97:	learn: 0.1951202	total: 23.4ms	remaining: 215ms
98:	learn: 0.1939291	total: 23.6ms	remaining: 215ms
99:	learn: 0.1928580	total: 23.9ms	remaining: 215ms
100:	learn: 0.1915827	total: 24.1ms	remaining: 215ms
101:	learn: 0.1900715	total: 24.4ms	remaining: 215ms
102:	learn: 0.1889386	total: 24.6ms	remaining: 215ms
103:	learn: 0.1876613	total: 24.9ms	remaining: 215ms
104:	learn: 0.1867954	total: 25.2ms	remaining: 214ms
105:	learn: 0.1860829	total: 25.3ms	remaining: 214ms
106:	learn: 0.1846754	total: 25.6ms	remaining: 214ms
107:	learn: 0.1832430	total: 25.9ms	remaining: 214ms
108:	l

400:	learn: 0.0571347	total: 105ms	remaining: 157ms
401:	learn: 0.0570814	total: 106ms	remaining: 157ms
402:	learn: 0.0567831	total: 106ms	remaining: 157ms
403:	learn: 0.0565582	total: 106ms	remaining: 157ms
404:	learn: 0.0565054	total: 107ms	remaining: 156ms
405:	learn: 0.0564534	total: 107ms	remaining: 156ms
406:	learn: 0.0561610	total: 107ms	remaining: 156ms
407:	learn: 0.0561096	total: 107ms	remaining: 156ms
408:	learn: 0.0558208	total: 108ms	remaining: 155ms
409:	learn: 0.0557699	total: 108ms	remaining: 155ms
410:	learn: 0.0554847	total: 108ms	remaining: 155ms
411:	learn: 0.0552702	total: 108ms	remaining: 155ms
412:	learn: 0.0551707	total: 109ms	remaining: 154ms
413:	learn: 0.0548909	total: 109ms	remaining: 154ms
414:	learn: 0.0547936	total: 109ms	remaining: 154ms
415:	learn: 0.0545169	total: 110ms	remaining: 154ms
416:	learn: 0.0542438	total: 110ms	remaining: 153ms
417:	learn: 0.0541940	total: 110ms	remaining: 153ms
418:	learn: 0.0539242	total: 110ms	remaining: 153ms
419:	learn: 

682:	learn: 0.0270620	total: 180ms	remaining: 83.4ms
683:	learn: 0.0269410	total: 180ms	remaining: 83.3ms
684:	learn: 0.0268932	total: 181ms	remaining: 83.1ms
685:	learn: 0.0267739	total: 181ms	remaining: 82.8ms
686:	learn: 0.0266560	total: 181ms	remaining: 82.6ms
687:	learn: 0.0266331	total: 182ms	remaining: 82.3ms
688:	learn: 0.0265163	total: 182ms	remaining: 82.1ms
689:	learn: 0.0264938	total: 182ms	remaining: 81.8ms
690:	learn: 0.0263782	total: 182ms	remaining: 81.6ms
691:	learn: 0.0263346	total: 183ms	remaining: 81.4ms
692:	learn: 0.0263123	total: 184ms	remaining: 81.4ms
693:	learn: 0.0261982	total: 185ms	remaining: 81.4ms
694:	learn: 0.0261762	total: 186ms	remaining: 81.4ms
695:	learn: 0.0261338	total: 186ms	remaining: 81.4ms
696:	learn: 0.0261126	total: 187ms	remaining: 81.3ms
697:	learn: 0.0259998	total: 188ms	remaining: 81.3ms
698:	learn: 0.0259788	total: 189ms	remaining: 81.3ms
699:	learn: 0.0259376	total: 189ms	remaining: 81.1ms
700:	learn: 0.0258263	total: 189ms	remaining: 

951:	learn: 0.0148047	total: 267ms	remaining: 13.5ms
952:	learn: 0.0147689	total: 267ms	remaining: 13.2ms
953:	learn: 0.0147143	total: 268ms	remaining: 12.9ms
954:	learn: 0.0146650	total: 268ms	remaining: 12.6ms
955:	learn: 0.0146244	total: 268ms	remaining: 12.3ms
956:	learn: 0.0145758	total: 268ms	remaining: 12.1ms
957:	learn: 0.0145210	total: 269ms	remaining: 11.8ms
958:	learn: 0.0144886	total: 269ms	remaining: 11.5ms
959:	learn: 0.0144412	total: 269ms	remaining: 11.2ms
960:	learn: 0.0144016	total: 270ms	remaining: 10.9ms
961:	learn: 0.0143548	total: 270ms	remaining: 10.7ms
962:	learn: 0.0143116	total: 270ms	remaining: 10.4ms
963:	learn: 0.0142798	total: 270ms	remaining: 10.1ms
964:	learn: 0.0142339	total: 271ms	remaining: 9.82ms
965:	learn: 0.0141840	total: 271ms	remaining: 9.54ms
966:	learn: 0.0141456	total: 271ms	remaining: 9.26ms
967:	learn: 0.0141008	total: 272ms	remaining: 8.98ms
968:	learn: 0.0140567	total: 272ms	remaining: 8.7ms
969:	learn: 0.0140270	total: 272ms	remaining: 8

144:	learn: 0.0908384	total: 28ms	remaining: 165ms
145:	learn: 0.0901026	total: 28.8ms	remaining: 169ms
146:	learn: 0.0896471	total: 29.1ms	remaining: 169ms
147:	learn: 0.0888699	total: 29.4ms	remaining: 169ms
148:	learn: 0.0881624	total: 29.8ms	remaining: 170ms
149:	learn: 0.0872886	total: 30.2ms	remaining: 171ms
150:	learn: 0.0865874	total: 30.5ms	remaining: 171ms
151:	learn: 0.0861541	total: 30.7ms	remaining: 172ms
152:	learn: 0.0858226	total: 31ms	remaining: 171ms
153:	learn: 0.0855717	total: 31.2ms	remaining: 171ms
154:	learn: 0.0848520	total: 31.4ms	remaining: 171ms
155:	learn: 0.0841640	total: 31.6ms	remaining: 171ms
156:	learn: 0.0837654	total: 31.9ms	remaining: 171ms
157:	learn: 0.0833289	total: 32.1ms	remaining: 171ms
158:	learn: 0.0827345	total: 32.4ms	remaining: 171ms
159:	learn: 0.0823380	total: 32.7ms	remaining: 172ms
160:	learn: 0.0816194	total: 33ms	remaining: 172ms
161:	learn: 0.0812803	total: 33.3ms	remaining: 172ms
162:	learn: 0.0805926	total: 33.6ms	remaining: 173ms

481:	learn: 0.0288433	total: 111ms	remaining: 119ms
482:	learn: 0.0287714	total: 111ms	remaining: 119ms
483:	learn: 0.0287290	total: 112ms	remaining: 119ms
484:	learn: 0.0286586	total: 112ms	remaining: 119ms
485:	learn: 0.0285654	total: 112ms	remaining: 119ms
486:	learn: 0.0285047	total: 113ms	remaining: 119ms
487:	learn: 0.0283660	total: 113ms	remaining: 119ms
488:	learn: 0.0282511	total: 113ms	remaining: 118ms
489:	learn: 0.0281602	total: 114ms	remaining: 118ms
490:	learn: 0.0280912	total: 114ms	remaining: 118ms
491:	learn: 0.0280187	total: 115ms	remaining: 119ms
492:	learn: 0.0279515	total: 115ms	remaining: 118ms
493:	learn: 0.0278810	total: 116ms	remaining: 119ms
494:	learn: 0.0277138	total: 117ms	remaining: 119ms
495:	learn: 0.0276482	total: 117ms	remaining: 119ms
496:	learn: 0.0275630	total: 118ms	remaining: 120ms
497:	learn: 0.0275014	total: 119ms	remaining: 120ms
498:	learn: 0.0274104	total: 120ms	remaining: 120ms
499:	learn: 0.0273044	total: 120ms	remaining: 120ms
500:	learn: 

669:	learn: 0.0184473	total: 190ms	remaining: 93.4ms
670:	learn: 0.0184079	total: 190ms	remaining: 93.2ms
671:	learn: 0.0183697	total: 190ms	remaining: 92.9ms
672:	learn: 0.0183323	total: 191ms	remaining: 92.6ms
673:	learn: 0.0182961	total: 191ms	remaining: 92.3ms
674:	learn: 0.0182473	total: 191ms	remaining: 92ms
675:	learn: 0.0181992	total: 191ms	remaining: 91.7ms
676:	learn: 0.0181329	total: 192ms	remaining: 91.4ms
677:	learn: 0.0180679	total: 192ms	remaining: 91.1ms
678:	learn: 0.0180215	total: 192ms	remaining: 90.8ms
679:	learn: 0.0179758	total: 197ms	remaining: 92.8ms
680:	learn: 0.0179307	total: 197ms	remaining: 92.5ms
681:	learn: 0.0178753	total: 198ms	remaining: 92.2ms
682:	learn: 0.0178306	total: 198ms	remaining: 91.9ms
683:	learn: 0.0177864	total: 198ms	remaining: 91.6ms
684:	learn: 0.0177320	total: 198ms	remaining: 91.2ms
685:	learn: 0.0176883	total: 199ms	remaining: 90.9ms
686:	learn: 0.0176349	total: 199ms	remaining: 90.6ms
687:	learn: 0.0175402	total: 199ms	remaining: 90

996:	learn: 0.0089898	total: 275ms	remaining: 828us
997:	learn: 0.0089733	total: 276ms	remaining: 553us
998:	learn: 0.0089521	total: 276ms	remaining: 276us
999:	learn: 0.0089330	total: 277ms	remaining: 0us
Learning rate set to 0.027987
0:	learn: 0.8057135	total: 298us	remaining: 299ms
1:	learn: 0.7903377	total: 561us	remaining: 280ms
2:	learn: 0.7752277	total: 814us	remaining: 271ms
3:	learn: 0.7588164	total: 1.07ms	remaining: 266ms
4:	learn: 0.7445017	total: 1.29ms	remaining: 257ms
5:	learn: 0.7305212	total: 1.67ms	remaining: 276ms
6:	learn: 0.7160744	total: 1.94ms	remaining: 275ms
7:	learn: 0.7024147	total: 2.17ms	remaining: 269ms
8:	learn: 0.6885255	total: 2.44ms	remaining: 268ms
9:	learn: 0.6753496	total: 2.67ms	remaining: 264ms
10:	learn: 0.6629949	total: 2.88ms	remaining: 259ms
11:	learn: 0.6507197	total: 3.09ms	remaining: 255ms
12:	learn: 0.6380109	total: 3.31ms	remaining: 251ms
13:	learn: 0.6274541	total: 3.54ms	remaining: 250ms
14:	learn: 0.6154715	total: 4.26ms	remaining: 280

291:	learn: 0.0664185	total: 59.9ms	remaining: 145ms
292:	learn: 0.0660253	total: 60.5ms	remaining: 146ms
293:	learn: 0.0656378	total: 60.8ms	remaining: 146ms
294:	learn: 0.0655250	total: 61ms	remaining: 146ms
295:	learn: 0.0653005	total: 61.3ms	remaining: 146ms
296:	learn: 0.0649204	total: 61.5ms	remaining: 146ms
297:	learn: 0.0647916	total: 61.8ms	remaining: 146ms
298:	learn: 0.0644178	total: 62ms	remaining: 145ms
299:	learn: 0.0640494	total: 62.3ms	remaining: 145ms
300:	learn: 0.0637643	total: 62.6ms	remaining: 145ms
301:	learn: 0.0635505	total: 63ms	remaining: 146ms
302:	learn: 0.0633425	total: 63.3ms	remaining: 146ms
303:	learn: 0.0631740	total: 63.5ms	remaining: 145ms
304:	learn: 0.0629722	total: 63.8ms	remaining: 145ms
305:	learn: 0.0628077	total: 64ms	remaining: 145ms
306:	learn: 0.0626816	total: 64.3ms	remaining: 145ms
307:	learn: 0.0624860	total: 64.7ms	remaining: 145ms
308:	learn: 0.0622921	total: 65.2ms	remaining: 146ms
309:	learn: 0.0621033	total: 65.6ms	remaining: 146ms
3

631:	learn: 0.0250181	total: 143ms	remaining: 83.4ms
632:	learn: 0.0249280	total: 144ms	remaining: 83.2ms
633:	learn: 0.0248246	total: 144ms	remaining: 83.1ms
634:	learn: 0.0247840	total: 144ms	remaining: 82.8ms
635:	learn: 0.0247565	total: 144ms	remaining: 82.6ms
636:	learn: 0.0247200	total: 145ms	remaining: 82.4ms
637:	learn: 0.0246842	total: 145ms	remaining: 82.2ms
638:	learn: 0.0246118	total: 145ms	remaining: 82ms
639:	learn: 0.0246028	total: 145ms	remaining: 81.8ms
640:	learn: 0.0245765	total: 146ms	remaining: 81.6ms
641:	learn: 0.0244989	total: 146ms	remaining: 81.4ms
642:	learn: 0.0244605	total: 146ms	remaining: 81.2ms
643:	learn: 0.0244187	total: 147ms	remaining: 81ms
644:	learn: 0.0243182	total: 147ms	remaining: 80.8ms
645:	learn: 0.0243095	total: 147ms	remaining: 80.6ms
646:	learn: 0.0242221	total: 147ms	remaining: 80.4ms
647:	learn: 0.0241962	total: 148ms	remaining: 80.2ms
648:	learn: 0.0241587	total: 148ms	remaining: 80.1ms
649:	learn: 0.0241335	total: 148ms	remaining: 79.8

963:	learn: 0.0113864	total: 219ms	remaining: 8.17ms
964:	learn: 0.0113535	total: 219ms	remaining: 7.94ms
965:	learn: 0.0113490	total: 219ms	remaining: 7.72ms
966:	learn: 0.0113182	total: 220ms	remaining: 7.49ms
967:	learn: 0.0113032	total: 220ms	remaining: 7.27ms
968:	learn: 0.0112800	total: 220ms	remaining: 7.05ms
969:	learn: 0.0112515	total: 221ms	remaining: 6.82ms
970:	learn: 0.0112118	total: 221ms	remaining: 6.6ms
971:	learn: 0.0111892	total: 221ms	remaining: 6.37ms
972:	learn: 0.0111848	total: 221ms	remaining: 6.14ms
973:	learn: 0.0111558	total: 222ms	remaining: 5.92ms
974:	learn: 0.0111171	total: 222ms	remaining: 5.7ms
975:	learn: 0.0110953	total: 222ms	remaining: 5.47ms
976:	learn: 0.0110822	total: 223ms	remaining: 5.24ms
977:	learn: 0.0110456	total: 223ms	remaining: 5.01ms
978:	learn: 0.0110256	total: 223ms	remaining: 4.79ms
979:	learn: 0.0109898	total: 224ms	remaining: 4.56ms
980:	learn: 0.0109700	total: 224ms	remaining: 4.33ms
981:	learn: 0.0109441	total: 224ms	remaining: 4.

186:	learn: 0.1028007	total: 52.8ms	remaining: 230ms
187:	learn: 0.1018822	total: 53.1ms	remaining: 229ms
188:	learn: 0.1009890	total: 53.4ms	remaining: 229ms
189:	learn: 0.1001789	total: 53.6ms	remaining: 229ms
190:	learn: 0.0996237	total: 53.9ms	remaining: 228ms
191:	learn: 0.0991315	total: 54.2ms	remaining: 228ms
192:	learn: 0.0982991	total: 54.8ms	remaining: 229ms
193:	learn: 0.0980264	total: 55.2ms	remaining: 229ms
194:	learn: 0.0971558	total: 55.5ms	remaining: 229ms
195:	learn: 0.0969990	total: 55.8ms	remaining: 229ms
196:	learn: 0.0964757	total: 56.1ms	remaining: 229ms
197:	learn: 0.0962765	total: 56.6ms	remaining: 229ms
198:	learn: 0.0960433	total: 56.9ms	remaining: 229ms
199:	learn: 0.0952397	total: 57.1ms	remaining: 229ms
200:	learn: 0.0948589	total: 57.4ms	remaining: 228ms
201:	learn: 0.0942707	total: 57.7ms	remaining: 228ms
202:	learn: 0.0935716	total: 58ms	remaining: 228ms
203:	learn: 0.0927724	total: 58.2ms	remaining: 227ms
204:	learn: 0.0923412	total: 58.5ms	remaining: 2

439:	learn: 0.0446625	total: 129ms	remaining: 164ms
440:	learn: 0.0445426	total: 130ms	remaining: 165ms
441:	learn: 0.0443244	total: 130ms	remaining: 164ms
442:	learn: 0.0441085	total: 131ms	remaining: 164ms
443:	learn: 0.0440565	total: 131ms	remaining: 164ms
444:	learn: 0.0439397	total: 131ms	remaining: 164ms
445:	learn: 0.0437260	total: 132ms	remaining: 163ms
446:	learn: 0.0435667	total: 132ms	remaining: 163ms
447:	learn: 0.0433840	total: 132ms	remaining: 163ms
448:	learn: 0.0432645	total: 132ms	remaining: 163ms
449:	learn: 0.0430661	total: 133ms	remaining: 162ms
450:	learn: 0.0428703	total: 133ms	remaining: 162ms
451:	learn: 0.0426955	total: 133ms	remaining: 162ms
452:	learn: 0.0425015	total: 134ms	remaining: 161ms
453:	learn: 0.0423874	total: 134ms	remaining: 161ms
454:	learn: 0.0421958	total: 134ms	remaining: 161ms
455:	learn: 0.0420281	total: 134ms	remaining: 160ms
456:	learn: 0.0418386	total: 135ms	remaining: 160ms
457:	learn: 0.0417902	total: 135ms	remaining: 160ms
458:	learn: 

769:	learn: 0.0191485	total: 214ms	remaining: 63.9ms
770:	learn: 0.0191442	total: 214ms	remaining: 63.7ms
771:	learn: 0.0191134	total: 215ms	remaining: 63.4ms
772:	learn: 0.0191092	total: 215ms	remaining: 63.1ms
773:	learn: 0.0190789	total: 215ms	remaining: 62.8ms
774:	learn: 0.0190672	total: 215ms	remaining: 62.5ms
775:	learn: 0.0190630	total: 216ms	remaining: 62.2ms
776:	learn: 0.0190367	total: 216ms	remaining: 61.9ms
777:	learn: 0.0189571	total: 216ms	remaining: 61.6ms
778:	learn: 0.0188895	total: 219ms	remaining: 62.2ms
779:	learn: 0.0188619	total: 220ms	remaining: 61.9ms
780:	learn: 0.0188393	total: 220ms	remaining: 61.7ms
781:	learn: 0.0188209	total: 220ms	remaining: 61.4ms
782:	learn: 0.0188028	total: 220ms	remaining: 61.1ms
783:	learn: 0.0187987	total: 221ms	remaining: 60.8ms
784:	learn: 0.0187735	total: 221ms	remaining: 60.5ms
785:	learn: 0.0187694	total: 221ms	remaining: 60.2ms
786:	learn: 0.0187440	total: 221ms	remaining: 59.9ms
787:	learn: 0.0186725	total: 222ms	remaining: 

Training Accuracy: 92.10 %
Training data Standard Deviation: 4.99 %
r_2_score =  0.984711472610612
MSE =  0.10376710670639222
RMSE =  0.01076761243421579
Compare with Predict and actual
 [[1.   1.16]
 [0.   0.17]
 [2.   1.82]
 [1.   1.11]
 [1.   1.06]
 [0.   0.12]
 [1.   0.96]
 [2.   1.87]
 [1.   1.29]
 [1.   1.02]]
